#!/usr/bin/with-contenv bash
echo >&2 "starting frp"

export frp_token=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 13)
echo "frp token is `${frp_token}`"
sed -i 's!\(token = \).*$!\1'"$frp_token"'!' /etc/frps.ini

exec /usr/local/bin/frps -c /etc/frps.ini 2>&1
